REM ******** TABLA ALMACENES: *********** 

DROP TABLE ALMACENES CASCADE CONSTRAINTS; 

CREATE TABLE ALMACENES (
 	ALM_NO  NUMBER(2),
	ANOMBRE  VARCHAR2(14), 
 	LOC      VARCHAR2(14),
	CONSTRAINT ALM_PK PRIMARY KEY (ALM_NO)
	);

INSERT INTO ALMACENES VALUES (10,'VENTAS SUR','SEVILLA');
INSERT INTO ALMACENES VALUES (20,'REPUESTOS','BILBAO');
INSERT INTO ALMACENES VALUES (30,'VENTAS ESTE','BARCELONA');
INSERT INTO ALMACENES VALUES (40,'PRODUCCION','BILBAO');
INSERT INTO ALMACENES VALUES (50,'RESIDUOS','BURGOS');

COMMIT;